### ISSUE TITLE
CI: Repair code coverage tool

### ISSUE THREAD

**Issue by olleolleolle** [savonrb/gyoku#79]
In GitHub Actions output, examples:

```
Coveralls encountered an exception:
NoMethodError
undefined method `coverage' for #<SimpleCov::SourceFile:0x00007f3142fd0cd0 @filename="/home/runner/work/gyoku/gyoku/lib/gyoku.rb", @coverage_data={"lines"=>[1, 1, nil, 1, nil, nil, 1, 4, nil, nil, nil, 1, 6, nil, nil, nil]}>

          properties[:coverage] = file.coverage
                                      ^^^^^^^^^
Did you mean?  coverage_data
/home/runner/work/gyoku/gyoku/vendor/bundle/ruby/3.1.0/gems/coveralls-0.7.2/lib/coveralls/simplecov.rb:50:in `block in format'
/opt/hostedtoolcache/Ruby/3.1.1/x64/lib/ruby/3.1.0/forwardable.rb:238:in `each'
/opt/hostedtoolcache/Ruby/3.1.1/x64/lib/ruby/3.1.0/forwardable.rb:238:in `each'
/home/runner/work/gyoku/gyoku/vendor/bundle/ruby/3.1.0/gems/coveralls-0.7.2/lib/coveralls/simplecov.rb:40:in `format'
/home/runner/work/gyoku/gyoku/vendor/bundle/ruby/3.1.0/gems/simplecov-0.21.2/lib/simplecov/result.rb:51:in `format!'
/home/runner/work/gyoku/gyoku/vendor/bundle/ruby/3.1.0/gems/simplecov-0.21.2/lib/simplecov/configuration.rb:197:in `block in at_exit'
/home/runner/work/gyoku/gyoku/vendor/bundle/ruby/3.1.0/gems/simplecov-0.21.2/lib/simplecov.rb:189:in `run_exit_tasks!'
/home/runner/work/gyoku/gyoku/vendor/bundle/ruby/3.1.0/gems/simplecov-0.21.2/lib/simplecov.rb:179:in `at_exit_behavior'
/home/runner/work/gyoku/gyoku/vendor/bundle/ruby/3.1.0/gems/simplecov-0.21.2/lib/simplecov/defaults.rb:30:in `block in <top (required)>'
```

**Comment by pcai** [comment]
Closing as completed — coverage reporting was wired up via the coveralls GitHub Action in 2023 (#87/#88).
